config/routes.rb
Hackathon::Application.routes.draw do
  resources :donors

  resources :donations

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :amount, :date, :donorid
  belongs_to :donor
end

def sum=(amount)
  @sum = amount;
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :donations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  # GET /donors
  # GET /donors.json
  def index
    @donors = Donor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donors }
    end
  end

  # GET /donors/1
  # GET /donors/1.json
  def show
    @donor = Donor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/new
  # GET /donors/new.json
  def new
    @donor = Donor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donor }
    end
  end

  # GET /donors/1/edit
  def edit
    @donor = Donor.find(params[:id])
  end

  # POST /donors
  # POST /donors.json
  def create
    @donor = Donor.new(params[:donor])

    respond_to do |format|
      if @donor.save
        format.html { redirect_to @donor, notice: 'Donor was successfully created.' }
        format.json { render json: @donor, status: :created, location: @donor }
      else
        format.html { render action: "new" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donors/1
  # PUT /donors/1.json
  def update
    @donor = Donor.find(params[:id])

    respond_to do |format|
      if @donor.update_attributes(params[:donor])
        format.html { redirect_to @donor, notice: 'Donor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donors/1
  # DELETE /donors/1.json
  def destroy
    @donor = Donor.find(params[:id])
    @donor.destroy

    respond_to do |format|
      format.html { redirect_to donors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :donorid %><br />
    <%= f.number_field :donorid %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <tr>
    <th>Donorid</th>
    <th>Amount</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.donorid %></td>
    <td>$<%= donation.amount %></td>
    <td><%= donation.date %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

Total Donations: <%= @donation.sum%>

<br />

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Donorid:</b>
  <%= @donation.donorid %>
</p>

<p>
  <b>Amount:</b>
  <%= @donation.amount %>
</p>

<p>
  <b>Date:</b>
  <%= @donation.date %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/donors/_form.html.erb
<%= form_for(@donor) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/edit.html.erb
<h1>Editing donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/index.html.erb
<h1>Listing donors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donors.each do |donor| %>
  <tr>
    <td><%= donor.name %></td>
    <td><%= donor.email %></td>
    <td><%= link_to 'Show', donor %></td>
    <td><%= link_to 'Edit', edit_donor_path(donor) %></td>
    <td><%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donor', new_donor_path %>

app/views/donors/new.html.erb
<h1>New donor</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/donors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @donor.name %>
</p>

<p>
  <b>Email:</b>
  <%= @donor.email %>
</p>


<%= link_to 'Edit', edit_donor_path(@donor) %> |
<%= link_to 'Back', donors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackathon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>